### ISSUE TITLE
Generated Command doesnt work

### ISSUE THREAD

**Issue by Ferox-Stylo** [eszesbalint/bdstudio#1] opened 2023-06-11 21:11 UTC
The generated Command isn't working (shown red in the command block)

The command sometimes contains NaN. This happends when a block entity doesn't has a value in some of its transformation parameters. I don't know how I caused this bug.

One of my red sandstone blocks is causing the error. I have linked you my full project and the bugged block only as files. 
(I had to change the file to a txt, because github doesn't support your custom file type)

[bugged_block_only.txt](https://github.com/eszesbalint/bdstudio/files/11715723/bugged_block_only.txt)
[bugged_building.txt](https://github.com/eszesbalint/bdstudio/files/11715724/bugged_building.txt)

**Comment by eszesbalint** [comment] 2023-06-12 05:57
I was able to reproduce the bug. It turns out, if you set scaling values to zeros, then three.js can't decompose the transformation matrices to position, rotation, scale (which now that I think about makes perfect sense). That's how those NaN values appear. The easiest solution will be to set the minimum scale to a really small but non-zero value. Thanks for your report! I will make sure to fix that in a future release.

**Comment by eszesbalint** [comment] 2023-06-12 16:27
Fixed in Beta 1.1.1

**Closed by eszesbalint** 2023-06-12 16:27 UTC
